# Generated by Django 4.2.2 on 2023-06-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_client_section',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
