# Generated by Django 4.2.2 on 2023-06-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service_service_why_amorserv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header_section',
            name='page_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
