# Generated by Django 4.2.2 on 2023-06-29 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_header_section_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_service_section',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
