# Generated by Django 4.2.2 on 2023-06-29 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_home_service_section_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home_client_section',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='home_overwhelmed_section',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
