# Generated by Django 4.2.2 on 2023-06-29 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_home_step_process_home_step_process_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('who_is_content', models.TextField(blank=True, max_length=500, null=True)),
                ('vision_image', models.FileField(blank=True, null=True, upload_to='')),
                ('vision_title', models.CharField(blank=True, max_length=50, null=True)),
                ('vision_content', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='About_partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(blank=True, max_length=50, null=True)),
                ('partner_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='About_team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_member_name', models.CharField(blank=True, max_length=50, null=True)),
                ('team_member_role', models.CharField(blank=True, max_length=50, null=True)),
                ('team_member_image', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='home_step_process_section',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
