# Generated by Django 4.2.2 on 2023-06-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_about_about_partners_about_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('who_is_amorserv_content', models.TextField(blank=True, max_length=500, null=True)),
                ('vision_image1', models.FileField(blank=True, null=True, upload_to='')),
                ('vision_title1', models.CharField(blank=True, max_length=50, null=True)),
                ('vision_content1', models.TextField(blank=True, max_length=200, null=True)),
                ('vision_image2', models.FileField(blank=True, null=True, upload_to='')),
                ('vision_title2', models.CharField(blank=True, max_length=50, null=True)),
                ('vision_content2', models.TextField(blank=True, max_length=200, null=True)),
                ('vision_image3', models.FileField(blank=True, null=True, upload_to='')),
                ('vision_title3', models.CharField(blank=True, max_length=50, null=True)),
                ('vision_content3', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
