# Generated by Django 4.2.2 on 2023-06-29 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_about_us_delete_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_partners',
            new_name='About_partner',
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'About Us'},
        ),
        migrations.AlterModelOptions(
            name='home_client_section',
            options={'verbose_name_plural': 'Home (Client Section)'},
        ),
        migrations.AlterModelOptions(
            name='home_happy_customer',
            options={'verbose_name_plural': 'Home (Happy Customer Section)'},
        ),
        migrations.AlterModelOptions(
            name='home_overwhelmed_section',
            options={'verbose_name_plural': 'Home (Feeling Overwhelmed Section)'},
        ),
        migrations.AlterModelOptions(
            name='home_proposal_section',
            options={'verbose_name_plural': 'Home (Proposal Section)'},
        ),
        migrations.AlterModelOptions(
            name='home_service_section',
            options={'verbose_name_plural': 'Home (Service Section)'},
        ),
        migrations.AlterModelOptions(
            name='home_step_process_section',
            options={'verbose_name_plural': 'Home (3 Step Process Section)'},
        ),
        migrations.AlterModelOptions(
            name='service_why_amorserv',
            options={'verbose_name_plural': 'Service (why amorserv)'},
        ),
    ]
