# Generated by Django 4.2.2 on 2023-06-29 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_about_partners_about_partner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_partner',
            options={'verbose_name_plural': 'About (Partners Section)'},
        ),
        migrations.AlterModelOptions(
            name='about_team',
            options={'verbose_name_plural': 'About (Team Members Section)'},
        ),
    ]
