# Generated by Django 4.2.2 on 2023-06-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_about_partner_options_alter_about_team_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('paragraph1_content', models.TextField(blank=True, max_length=500, null=True)),
                ('paragraph2_content', models.TextField(blank=True, max_length=500, null=True)),
                ('paragraph3_content', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
