# Generated by Django 4.2.2 on 2023-06-29 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('para1', models.TextField(blank=True, max_length=500, null=True)),
                ('para2', models.TextField(blank=True, max_length=500, null=True)),
                ('para3', models.TextField(blank=True, max_length=500, null=True)),
                ('para4', models.TextField(blank=True, max_length=500, null=True)),
                ('image1', models.FileField(blank=True, null=True, upload_to='')),
                ('image2', models.FileField(blank=True, null=True, upload_to='')),
                ('number_likes', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField(blank=True, max_length=500, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('blogPost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.blogpost')),
            ],
        ),
    ]
