# Generated by Django 4.2.2 on 2023-06-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_contact_enquiries_contact_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=150, null=True)),
                ('answer', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Information',
            },
        ),
        migrations.AlterModelOptions(
            name='blog_post',
            options={'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='blog_post_comment',
            options={'verbose_name_plural': 'Blog Post Comments'},
        ),
        migrations.AlterModelOptions(
            name='contact_info',
            options={'verbose_name_plural': 'Contact Information'},
        ),
    ]
