# Generated by Django 4.2.2 on 2023-06-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_faq_alter_blog_post_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms_Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Frequently Asked Question'},
        ),
        migrations.RenameField(
            model_name='header_section',
            old_name='page_type',
            new_name='PageType',
        ),
    ]
